import Link from 'next/link';
import AuthButton from '@/components/auth-button';

const modes = [
  ['Professional', 'Client work, decisions, and commitments.', 'bg-violet-400'],
  ['Academic', 'Learning, research, and deadlines.', 'bg-emerald-400'],
  ['Personal', 'The life and projects that are still yours.', 'bg-amber-400'],
];

export default function Home() {
  return <main className="landing-shell overflow-hidden">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 sm:px-8"><Link href="/" className="brand-mark">polynus<span>.</span></Link><div className="flex items-center gap-4"><Link href="#how-it-works" className="hidden text-sm text-slate-400 hover:text-white sm:block">How it works</Link><Link href="#roadmap" className="hidden text-sm text-slate-400 hover:text-white sm:block">Roadmap</Link><Link href="/connect" className="text-sm text-slate-200 hover:text-white">Sign in</Link><AuthButton label="Start free" /></div></nav>

    <section className="relative mx-auto grid max-w-7xl items-center gap-10 px-5 pb-20 pt-14 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:pb-28 lg:pt-24"><div className="hero-noise noise-one">GPT</div><div className="hero-noise noise-two">mail</div><div className="hero-noise noise-three">AI</div><div className="relative z-10"><p className="eyebrow">THE AI ERA HAS A CONTEXT PROBLEM</p><h1 className="mt-5 max-w-4xl text-5xl font-medium tracking-[-.06em] text-white sm:text-6xl lg:text-7xl">Are you using AI <em className="font-serif font-normal text-violet-300">- or is AI using your attention?</em></h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-slate-400">Every new chat promises leverage. But across assistants, messages, projects, and life, the things that matter can disappear into the noise. Polynus gives your day its shape back.</p><div className="mt-9 flex flex-wrap gap-3"><AuthButton label="See my daily command center"/><a href="#how-it-works" className="button-quiet">How Polynus works <span aria-hidden="true">↓</span></a></div><p className="mt-7 text-xs text-slate-500">Built for clarity. Private by design. You choose what Polynus can see.</p></div><div className="relative z-10"><div className="orbit-stage" aria-label="An original abstract visualization of Polynus organizing your modes"><div className="orbit-glow"/><div className="orbit-ring orbit-ring-one"/><div className="orbit-ring orbit-ring-two"/><div className="orbit-ring orbit-ring-three"/><div className="orbit-core"><span>your day</span><strong>Polynus</strong></div><div className="orbit-node orbit-violet"><span>work</span></div><div className="orbit-node orbit-green"><span>learn</span></div><div className="orbit-node orbit-amber"><span>life</span></div><div className="orbit-particle particle-one"/><div className="orbit-particle particle-two"/><div className="orbit-particle particle-three"/></div></div></section>

    <section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8"><div className="problem-band"><p className="eyebrow">CONTEXT IS EXPENSIVE</p><h2>More AI tools should create more momentum.<br className="hidden sm:block"/> Instead, they can create more places to lose it.</h2><div className="mt-8 grid gap-4 sm:grid-cols-3"><div><strong>Too many inputs</strong><span>Chats, inboxes, documents, and meetings all ask for attention.</span></div><div><strong>Too much switching</strong><span>What matters in one mode is buried by activity in another.</span></div><div><strong>Too little follow-through</strong><span>Important commitments become another forgotten tab.</span></div></div></div></section>

    <section id="how-it-works" className="landing-section"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="max-w-2xl"><p className="eyebrow">POLYNUS RESTORES THE SIGNAL</p><h2 className="mt-4 text-4xl font-medium tracking-[-.05em] text-white sm:text-5xl">One calm view of what deserves your attention next.</h2></div><div className="mt-14 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 md:grid-cols-3">{[['01','Understand','Polynus reads user-approved AI context and extracts real tasks - no invented to-dos.'],['02','Separate','It organizes commitments by the mode they belong to, not simply by the app that created them.'],['03','Focus','Start each day with priorities and a focused plan, then go deeper into the context when you need it.']].map(([number,title,copy])=><article key={number} className="bg-[#10111b] p-7 sm:p-9"><p className="font-mono text-xs text-violet-300">{number}</p><h3 className="mt-12 text-xl font-medium text-white">{title}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed text-slate-400">{copy}</p></article>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">YOUR REALITY HAS MODES</p><h2 className="mt-4 text-4xl font-medium tracking-[-.05em] text-white">You should not have to become one person to be organized.</h2><p className="mt-5 max-w-md leading-relaxed text-slate-400">Polynus protects the boundaries between the work you do, the things you are learning, and the life you are building.</p></div><div className="mode-stack">{modes.map(([title,copy,color], index)=><article className="mode-story-card" key={title}><span className={`h-3 w-3 rounded-full ${color}`}/><div><h3>{title}</h3><p>{copy}</p></div><b>0{index + 1}</b></article>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="integration-panel"><div><p className="eyebrow">ONE INTENTIONAL LAYER</p><h2>Polynus sits between your inputs and your attention.</h2><p>It does not ask you to replace the tools you use. It helps you understand what they are asking of you.</p></div><div className="integration-grid"><div className="integration-card live"><b>✦</b><span>AI conversations</span><small>Available now</small></div><div className="integration-card"><b>@</b><span>Email</span><small>Planned</small></div><div className="integration-card"><b>□</b><span>Calendar</span><small>Planned</small></div><div className="integration-card"><b>↗</b><span>Documents</span><small>Planned</small></div></div></div></section>

    <section className="landing-section"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">BUILT TO EARN TRUST</p><h2 className="mt-4 text-4xl font-medium tracking-[-.05em] text-white">Helpful, not invasive.</h2></div><p className="max-w-md text-sm leading-relaxed text-slate-400">Polynus is designed to work with data you explicitly approve. It surfaces commitments without turning your private life into a surveillance feed.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{[['User-approved context','You decide which sources and conversations are in scope.'],['No invented tasks','The dashboard is grounded in imported context and its source.'],['Human control first','Future automation will always begin with review and approval.']].map(([title,copy])=><div key={title} className="trust-card"><span>✦</span><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section>

    <section id="roadmap" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><p className="eyebrow">FROM CLARITY TO ACTION</p><h2 className="mt-4 max-w-2xl text-4xl font-medium tracking-[-.05em] text-white sm:text-5xl">A careful roadmap for a more capable personal operating layer.</h2><div className="mt-12 grid gap-4 md:grid-cols-3"><article className="roadmap-card roadmap-now"><span>NOW · BUILD WEEK MVP</span><h3>Understand</h3><p>Imported AI context, task extraction, three modes, time visibility, and focused daily recommendations.</p></article><article className="roadmap-card"><span>NEXT · CONNECT</span><h3>See the whole day</h3><p>Permissioned Gmail, Outlook, Calendar, Drive, and other sources - always organized by intent.</p></article><article className="roadmap-card"><span>LATER · ASSIST</span><h3>Move work forward</h3><p>User-approved task drafts, reminders, scheduling support, and carefully scoped automations.</p></article></div></section>

    <section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8"><div className="final-cta"><p className="eyebrow">MAKE SPACE FOR WHAT MATTERS</p><h2>Stop managing tabs.<br/><em>Start managing outcomes.</em></h2><p>Try the Polynus Daily Command Center.</p><AuthButton label="Create your workspace" /></div></section><footer className="border-t border-white/10 px-5 py-8 text-center text-xs text-slate-600">Polynus - your daily command center for many realities.</footer>
  </main>;
}
