'use client';
import { useEffect, useState } from 'react'; import { PieChart, Pie, Cell, ResponsiveContainer } from 'recharts';
type Mode='professional'|'academic'|'personal'; const config:Record<Mode,{label:string;color:string,ring:string}>={professional:{label:'Professional',color:'#9B5CFF',ring:'border-violet-400/30'},academic:{label:'Academic',color:'#36D399',ring:'border-emerald-400/30'},personal:{label:'Personal',color:'#FB923C',ring:'border-orange-400/30'}};
type Data={connected:string[];cards:{mode:Mode; totalSeconds:number; lastActivity:string|null; usage:{provider:string;seconds:number}[];tasks:{id:string;title:string;source_provider:string}[]}[];recommendation:string|null};
const fmt=(s:number)=>s>=3600?`${(s/3600).toFixed(s%3600?1:0)}h`:`${Math.round(s/60)}m`;
export default function Dashboard(){const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(false); const load=()=>fetch('/api/dashboard').then(r=>r.json()).then(setData); useEffect(load,[]);
const sync=async()=>{setLoading(true); await fetch('/api/sync',{method:'POST'}); await load(); setLoading(false)};
return <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><nav className="mb-14 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.26em] text-violet-300">Polynus</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Your AI life, in balance.</h1></div><div className="flex gap-2"><a href="/connect" className="rounded-xl border border-white/15 px-4 py-2 text-sm hover:bg-white/10">Connections {data && <span className="text-emerald-300">({data.connected.length})</span>}</a><button onClick={sync} disabled={loading} className="rounded-xl bg-violet-500 px-4 py-2 text-sm font-medium hover:bg-violet-400 disabled:opacity-60">{loading?'Syncing…':'Refresh insights'}</button></div></nav>
<section className="mb-7"><p className="text-sm text-slate-400">Today’s focus</p><h2 className="text-3xl font-semibold">See where your AI time goes.</h2></section>
<div className="grid gap-5 lg:grid-cols-3">{data?.cards.map(card=>{const c=config[card.mode], chart=card.usage.length?card.usage:[{provider:'No activity',seconds:1}]; return <article key={card.mode} className={`panel border-t-2 ${c.ring} p-6`}><div className="flex justify-between"><div><p className="text-sm font-medium" style={{color:c.color}}>{c.label}</p><p className="mt-1 text-3xl font-semibold">{fmt(card.totalSeconds)}</p><p className="text-xs text-slate-500">time spent today</p></div><div className="h-20 w-20"><ResponsiveContainer><PieChart><Pie data={chart} dataKey="seconds" innerRadius={24} outerRadius={37} paddingAngle={3}>{chart.map((_,i)=><Cell key={i} fill={i===0?c.color:['#60a5fa','#f472b6','#facc15'][i%3]}/>)}</Pie></PieChart></ResponsiveContainer></div></div><div className="mt-4 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-400">{card.usage.map((u,i)=><span key={u.provider}><i className="mr-1 inline-block h-2 w-2 rounded-full" style={{background:i===0?c.color:['#60a5fa','#f472b6'][i%2]}}/>{u.provider} {Math.round(u.seconds/Math.max(card.totalSeconds,1)*100)}%</span>)}</div><div className="mt-6 border-t border-white/10 pt-4"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-500">Pending tasks</p>{card.tasks.length?<ul className="space-y-2">{card.tasks.slice(0,3).map(t=><li key={t.id} className="flex gap-2 text-sm text-slate-200"><span className="mt-1 h-3.5 w-3.5 rounded border border-white/30"/>{t.title}</li>)}</ul>:<p className="text-sm text-slate-500">No pending tasks yet.</p>}</div><p className="mt-5 text-xs text-slate-500">{card.lastActivity?`Last activity ${new Date(card.lastActivity).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`:'No activity today'}</p></article>})}</div>
<section className="panel mt-7 p-6"><p className="text-sm font-medium text-amber-300">Recommendations</p><p className="mt-2 max-w-3xl text-lg leading-relaxed text-slate-200">{data?.recommendation ?? 'Connect a provider and refresh insights to receive a tailored recommendation.'}</p></section><p className="mt-8 text-center text-xs text-slate-600">Polynus keeps only the data you explicitly import. Disconnect or delete your data anytime.</p></main>}
